"""empty message

Revision ID: 6d92803a3f26
Revises: 
Create Date: 2022-05-30 12:08:27.837390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d92803a3f26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('Users', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_Users_token'), 'Users', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_token'), table_name='Users')
    op.drop_column('Users', 'token_expiration')
    op.drop_column('Users', 'token')
    # ### end Alembic commands ###
