"""empty message

Revision ID: f0c2cae54cb1
Revises: 0be486883e5e
Create Date: 2022-06-03 19:16:40.222776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c2cae54cb1'
down_revision = '0be486883e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('api_key', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'api_key')
    # ### end Alembic commands ###
